definitions:
  handlers.CodeRequest:
    description: Запрос для отправки кода подтверждения из Telegram
    properties:
      code:
        example: "12345"
        type: string
    required:
    - code
    type: object
  handlers.ErrorResponse:
    description: Структура для возврата ошибок
    properties:
      error:
        example: error message
        type: string
    type: object
  handlers.PasswordRequest:
    description: Запрос для отправки пароля двухфакторной аутентификации
    properties:
      password:
        example: my2fapassword
        type: string
    required:
    - password
    type: object
  handlers.PhoneRequest:
    description: Запрос для отправки номера телефона при авторизации
    properties:
      phone_number:
        example: "+1234567890"
        type: string
    required:
    - phone_number
    type: object
  handlers.SessionResponse:
    description: SessionResponse структура для ответа о сессии
    properties:
      auth_state:
        type: string
    type: object
  handlers.TokenResponse:
    description: TokenResponse структура для возврата токена
    properties:
      expires_in:
        type: integer
      token:
        type: string
      token_type:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/session/status:
    get:
      description: Возвращает текущий статус сессии
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SessionResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      security:
      - Bearer: []
      summary: Получить статус сессии
      tags:
      - auth
  /auth/telegram/code:
    post:
      consumes:
      - application/json
      description: Отправляет код подтверждения из Telegram
      parameters:
      - description: Verification code
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.CodeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SessionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      security:
      - Bearer: []
      summary: Установить код подтверждения
      tags:
      - auth
  /auth/telegram/init:
    post:
      consumes:
      - application/json
      description: Создает Telegram клиент и обновляет статус сессии
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SessionResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      security:
      - Bearer: []
      summary: Инициализировать Telegram клиента
      tags:
      - auth
  /auth/telegram/password:
    post:
      consumes:
      - application/json
      description: Отправляет пароль двухфакторной аутентификации
      parameters:
      - description: Password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.PasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SessionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      security:
      - Bearer: []
      summary: Установить пароль
      tags:
      - auth
  /auth/telegram/phone:
    post:
      consumes:
      - application/json
      description: Отправляет номер телефона для авторизации в Telegram
      parameters:
      - description: Phone number
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.PhoneRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SessionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      security:
      - Bearer: []
      summary: Установить номер телефона для Telegram
      tags:
      - auth
  /auth/token:
    post:
      consumes:
      - application/json
      description: Создает JWT токен
      parameters:
      - description: Phone number
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.PhoneRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.TokenResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Получить токен авторизации
      tags:
      - auth
  /ping:
    get:
      description: endpoint для проверки что сервер работает
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Проверка работоспособности API
      tags:
      - health
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
